server:
  port: 11001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: guest
    url: jdbc:mysql://localhost:3306/mysql_view?allowMultiQueries=true&useUnicode&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&verifyServerCertificate=false&requireSSL=true
    password: guest_user
